### ISSUE TITLE
Change package selector to combined search + selector box

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#59]
# Description

All the user to search a term as well as scrolling through the list.

# Tasks

* [x] Add search box to filter the list
* [x] Check if we have a nicer name/title to display instead of current slug

**Comment by kravets-levko** [comment]
> Check if we have a nicer name/title to display instead of current slug

Currently we can only display slugs, because API does not return any other info. We can get package titles only if preload all package files or if enhance API

**Comment by pwalsh** [comment]
ok.

**Comment by pwalsh** [comment]
DONE
