### ISSUE TITLE
Dimensions should be actual dimensions as per Fiscal Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#63]
It is not clear how dimensions are actually being displayed, not how it relates to the declaration of dimensions in Fiscal Data Package. Of particular interest are dimensions with multiple attributes, dimensions that use `labelfor`, and dimensions that use `parent` (and, combinations of all).

Using some of the BOOST Fiscal Data Packages, ensure that dimensions are properly displayed and usable in the UI, in a way that relates to the dimensions in the Fiscal Data Packages.

**Example**:

How does [this dimension from the moldova dataset](https://github.com/openspending/fiscal-data-package-demos/blob/master/boost-moldova/datapackage.json#L199) get a) exposed via the API, and b) recontructed (if necessary) in the UI? I'd expect that, while in Babbage the dimension is broken up into its parts, that implementing code for user interfaces should be able to reconstruct the dimension as declared in Fiscal Data Package and present the data to the user as a single dimension, and not as the parts of the dimension.

cc @akariv

**Comment by akariv** [comment]
So I added new properties to the babbage model to record any transformation that's done to dimension, attribute and measure names while converting the FDP to the model.

 - `orig_attribute` - The original attribute name from the FDP
 - `orig_dimension` - The original dimension name from the FDP 
 - `orig_measure` - The original measure name from the FDP

Using these new properties to find the original dimension/attribute/measure from the FDP should allow you to find any property present in the FDP and missing in the model.
You can see these new properties in action [here](http://s145.okserver.org/api/3/cubes/boost-moldova/model).

**Comment by borysyuk** [comment]
as `display name` i have used attributes.column attribute.
 Perhaps in the next version of FDP @danfowler will introduce a display name for each attribute and dimension which will allow showing a better looking label.

DONE.
