### ISSUE TITLE
Implement drilldown

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#64]
I see that drilldown is not currently working in the Viewer vis components. It could be that we need to use this PR for babbage.ui to support that: https://github.com/openspending/babbage.ui/pull/15

Please investigate, so that we can implement drilldown queries via vis, and that they are part of state management.

**Comment by borysyuk** [comment]
done

**Comment by pwalsh** [comment]
FIXED. Maybe some bugs, but opening in separate issue.
