### ISSUE TITLE
Add authentication support 

### ISSUE THREAD

**Issue by akariv** [openspending/os-viewer#66]
Implement the logged-in user widget per the style guide, similar to what's been done in os-packager.

**Comment by pwalsh** [comment]
Using https://github.com/openspending/os-auth-client right @akariv 

Is this npm installable at present? I think @kravets-levko can move onto this after https://github.com/openspending/os-viewer/issues/59

**Comment by akariv** [comment]
No, no - it should be loaded as an javascript library straight from http://s145.okserver.org/permit/lib.js

Then you could get some inspiration (and probably improve what I did here):
- https://github.com/openspending/os-packager/blob/master/app/front/scripts/services/login.js
- https://github.com/openspending/os-packager/blob/master/app/views/partials/header.html

**Comment by pwalsh** [comment]
sababa ;)
