### ISSUE TITLE
Embeddable

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-viewer#9]
# Description

It is useful to be able to embed the Viewer app elsewhere. As long as the viewer can manage state ( #61  ), then embedding is basically a matter of exposing a route that returns the viewer without the header or the footer. 

# Tasks

* [x] Expose embed route: `{viewer_url}/embed/{:id}/{:state}`

**Comment by borysyuk** [comment]
@pwalsh Should I hide list of all packages in 'embedded' mode?

**Comment by pwalsh** [comment]
@borysyuk no. that is a good idea for a flag though. I'd say no now, but add a new issue to consider for future. good one.
